#!/bin/sh

### DEFAULT VALUES
path="texts"
author="Macropedius"
length=1
version="0.0.1"
# If empty will be set to random noun
file=""
title=""


### ARGUMENTS
while getopts 'a:f:t:l:' flag; do
  case "${flag}" in
    a) author="${OPTARG}" ;;
    f) file="$path/${OPTARG}" ;;
    t) title="${OPTARG}" ;;
    l) length="${OPTARG}" ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

# Random noun from WordNet
first_index=198 
last_index=$(wc -l < ../WordNet-3.0/dict/index.noun)
rand_index=$(jot -r 1  $first_index $last_index)
line=$(sed "${rand_index}q;d" ../WordNet-3.0/dict/index.noun)
set -- $line
noun=$1
t_noun=$(echo ${noun} | tr '[_]' ' ')

# Write to file
if [ -z "$title" ]; then
    title="$(tr '[:lower:]' '[:upper:]' <<< ${t_noun:0:1})${t_noun:1}"
fi

if [ -z "$file" ]; then
    file=$path/${noun}.txt
fi

echo $title > $file
echo "by $author" >> $file
echo " " >> $file

for ((i=0; i<=length; i++)); do
   ./random_sentence.sh >> $file
done
   
echo " " >> $file

# This should be in meta module
#echo "-------------------" >> $file
#echo "generated by generatetext.sh $version" >> $file
#wn $noun -n1 -a -synsn >> $file
#wn $verb -n1 -a -synsv >> $file
#wn $adj -n1 -a -synsa >> $file

#Console output
echo $file